export const NIANJING_COPY = {
  yearOverview: {
    ariaLabel: '年镜年度模块总览',
    title: '年度总览',
    subtitle: '先看整体年度节奏',
    summaryAriaLabel: '总体年度总览',
    summaryMeta: '年度主导',
    summaryCardAriaLabel: (year: number, nature: string) => `${year} 年总体年度 ${nature}`,
    focusAriaLabel: '具体关注年度展开',
    focusTitle: '具体关注',
    focusSubtitle: '按关注主题展开',
    focusedSubtitle: (label: string) => `${label} 的年度展开`,
    concern: '关注',
    now: '现在',
    pathTitle: '年度节奏 · 综合强弱导览',
    pathSubtitle: '先看十年节奏，再选年份查看详情',
    pathLegendAriaLabel: '关注维度导览图例',
    selectedEyebrow: '选中年度 · 主导相位',
    selectedSummaryFallback: '这一年没有可显示的阶段摘要。',
    selectedMeta: '年度主导',
    yearDetailTitle: '年度相位详情',
    favorable: '宜',
    guarded: '忌',
    monthNodes: '关键节点 · 月份',
    noNodes: '本年无显著节点',
    basisTitle: '长程相位摘要 · 生成依据',
    basisSubtitle: '为什么得出以上判断',
    basisLabels: {
      phase_band: '阶段带',
      dayun_boundary: '大运边界',
      annual_transition: '流年切换',
      monthly_transition: '流月切换',
      marker_cluster: '多重节点',
    },
    basisSummary: (count: number, first: string) =>
      first ? `${count} 条证据 · ${first}` : `${count} 条结构化证据`,
    phaseAriaLabel: (year: number, label: string, nature: string) =>
      `${year} ${label} ${nature}阶段`,
    markersAriaLabel: (year: number, label: string) => `${year} ${label} 拐点`,
  },
  timeline: {
    emptyNotice: '当前筛选下没有可显示的相位带。',
    ariaLabel: '按关注标签的长程相位带与拐点时间轴',
    now: '现在',
    currentSuffix: '期',
    clickToView: '点按查看',
    bandAriaLabel: (range: string, nature: string) => `${range} ${nature}期,点按查看说明`,
    markerAriaLabel: (date: string, kind: string) => `${date} ${kind},点按查看说明`,
    legendAriaLabel: '拐点 / 现在 图例',
  },
  readyView: {
    footerSummary: '长程相位摘要与生成依据',
  },
  hero: {
    ariaLabel: '当前长程相位',
    focusedEyebrow: (label: string) => `${label} · 此刻`,
    defaultEyebrow: '当前阶段 · 此刻',
    horizonSuffix: '展望',
    rowsAriaLabel: '各关注当前相位',
  },
  filter: {
    toolbarAriaLabel: '按关注筛选 / 相位图例',
    concernLegend: '关注',
    all: '全部',
    manageConcerns: '✎ 编辑关注',
    legendAriaLabel: '相位图例',
  },
  concernEditor: {
    ariaLabel: '管理关注',
    title: '管理关注',
    subtitle: '激活的关注会出现在时间轴上,独立计算相位带与拐点。',
    activeHeading: '已激活',
    addableHeading: '可添加',
    remove: '移除',
    add: '添加',
    addLimitTitle: (limit: number) => `已达激活上限 ${limit}`,
    customPlaceholder: '自定义关注,如「学业」「创业」',
  },
  detailDrawer: {
    close: '关闭',
    detailSuffix: '详情',
    phaseSuffix: '期',
    mainline: '阶段主线',
    signalsAriaLabel: '这一阶段的信号',
    worthRemembering: (duration: string) => `${duration}里最值得记住的信号`,
    guidanceTitle: '把这段时间用在这里',
    guardrailsTitle: '需要守住的边界',
    timePrefix: '时间',
    basis: (concernLabel: string) => `依据 当前关注「${concernLabel}」与年镜长程相位变化`,
    inflectionQuestion: (kind: string) => `${kind}是什么`,
    promptTitle: '本次提示',
    impactWindow: '影响窗口',
    eventRecorderHeading: '这个拐点前后发生过什么',
  },
} as const;
