export const NIANJING_COPY = {
  yearOverview: {
    ariaLabel: '年镜年度模块总览',
    title: '年度总览',
    subtitle: '按关注主题展开',
    concern: '关注',
    now: '现在',
    phaseAriaLabel: (year: number, label: string, nature: string) =>
      `${year} ${label} ${nature}阶段`,
    markersAriaLabel: (year: number, label: string) => `${year} ${label} 拐点`,
  },
  timeline: {
    emptyNotice: '当前筛选下没有可显示的相位带。',
    ariaLabel: '按关注标签的长程相位带与拐点时间轴',
    now: '现在',
    currentSuffix: '期',
    clickToView: '点按查看',
    bandAriaLabel: (range: string, nature: string) => `${range} ${nature}期,点按查看说明`,
    markerAriaLabel: (date: string, kind: string) => `${date} ${kind},点按查看说明`,
    legendAriaLabel: '拐点 / 现在 图例',
  },
  readyView: {
    footerSummary: '长程相位摘要与生成依据',
  },
  hero: {
    ariaLabel: '当前长程相位',
    focusedEyebrow: (label: string) => `${label} · 此刻`,
    defaultEyebrow: '当前阶段 · 此刻',
    horizonSuffix: '展望',
    rowsAriaLabel: '各关注当前相位',
  },
  filter: {
    toolbarAriaLabel: '按关注筛选 / 相位图例',
    concernLegend: '关注',
    all: '全部',
    manageConcerns: '✎ 编辑关注',
    legendAriaLabel: '相位图例',
  },
  concernEditor: {
    ariaLabel: '管理关注',
    title: '管理关注',
    subtitle: '激活的关注会出现在时间轴上,独立计算相位带与拐点。',
    activeHeading: '已激活',
    addableHeading: '可添加',
    remove: '移除',
    add: '添加',
    addLimitTitle: (limit: number) => `已达激活上限 ${limit}`,
    customPlaceholder: '自定义关注,如「学业」「创业」',
  },
  detailDrawer: {
    close: '关闭',
    detailSuffix: '详情',
    phaseSuffix: '期',
    mainline: '阶段主线',
    signalsAriaLabel: '这一阶段的信号',
    worthRemembering: (duration: string) => `${duration}里最值得记住的信号`,
    guidanceTitle: '把这段时间用在这里',
    guardrailsTitle: '需要守住的边界',
    timePrefix: '时间',
    basis: (concernLabel: string) => `依据 当前关注「${concernLabel}」与年镜长程相位变化`,
    inflectionQuestion: (kind: string) => `${kind}是什么`,
    promptTitle: '本次提示',
    impactWindow: '影响窗口',
    eventRecorderHeading: '这个拐点前后发生过什么',
  },
} as const;
