export const YUEJING_COPY = {
  todayHero: {
    ariaLabel: '今日总览',
    eyebrow: '今日 · 总览',
    rowsAriaLabel: '今日各关注倾向',
    pending: '待生成',
    detailButton: '查看完整解读',
  },
  filter: {
    toolbarAriaLabel: '按关注筛选 / 倾向图例',
    concernAriaLabel: '关注',
    concernLabel: '关注',
    all: '全部',
    manageConcerns: '✎ 编辑关注',
    legendAriaLabel: '倾向图例',
  },
  concernEditor: {
    ariaLabel: '管理关注',
    title: '管理关注',
    subtitle: '激活的关注会按日纳入 30 日推算，并独立着色每天的倾向。',
    activeHeading: '已激活',
    addableHeading: '可添加',
    remove: '移除',
    add: '添加',
    addLimitTitle: (limit: number) => `已达激活上限 ${limit}`,
    customPlaceholder: '自定义关注,如「学业」「创业」',
  },
  calendar: {
    emptyNotice: '当前关注中，月镜 30 日窗口没有可显示的日历单元。',
    ariaLabel: '30 日日历',
    gridAriaLabel: '30 日日历网格',
    today: '今日',
    hasRecordAriaLabel: '已有记录',
    dayAriaLabel: (date: string, calendarMarkerLabel: string | null, tendencyLabel: string | null) =>
      [date, calendarMarkerLabel, tendencyLabel].filter(Boolean).join(' · '),
  },
  dayPanel: {
    close: '关闭',
    detailAriaLabel: (day: string, weekday: string) => `${day} ${weekday} 详情`,
    dayKindLabels: {
      past: '已过',
      today: '今日',
      future: '未来',
    },
    calendarDetails: {
      ariaLabel: '通用历法',
      title: '通用历法',
      lunar: '农历',
      ganzhi: '干支',
      solarTerm: '节气',
      festivals: '节日',
    },
    currentTendency: '当日倾向',
    emptyTendency: '本日还没有推算倾向。点击右上「生成今日」开始。',
    entryHeadings: {
      past: '记一笔事件',
      today: '记一笔今日观察',
      future: '记一笔计划项',
    },
    entryPlaceholders: {
      memory: '这一天发生了什么…',
      plan: '这一天计划…',
    },
    saveLabels: {
      memory: '保存事件',
      plan: '保存计划',
    },
    recordKinds: {
      memory: '事件',
      plan: '计划',
    },
    recordsTitle: (count: number) => `已记录 (${count})`,
    recordsEmpty: '这一天还没有记录。',
    recordsAriaLabel: (kind: string) => `已记录的${kind}`,
    editRecordContent: '编辑记录内容',
    askThisRecord: '去问镜问这条',
    edit: '编辑',
    delete: '删除',
    cancel: '取消',
    save: '保存',
    editRecordAriaLabel: (kind: string) => `编辑这条${kind}`,
    deleteRecordAriaLabel: (kind: string) => `删除这条${kind}`,
    deleteTitle: (kind: string) => `删除这条${kind}？`,
    deleteMessage: (body: string) =>
      `「${body}」将被永久删除，解读时不再引用。此操作不可撤销。`,
  },
  monthPanel: {
    close: '关闭',
    ariaLabel: (range: string) => `${range} 完整解读`,
    title: '30 日解读',
    meta: (range: string, generatedDays: number, activeTags: number) =>
      `${range} · 已生成 ${generatedDays}/30 日 · ${activeTags} 个关注`,
    empty:
      '当前 30 日窗口还没有可解读的月镜数据。生成后这里会按关注给出本期主线、关键窗口、30 日节奏、关注行动和复盘问题。',
    mainline: '本期主线',
    rhythmOverview: '30 日节奏概览',
    dailyRhythmAriaLabel: (range: string) => `${range} 每日节奏`,
    pending: '待生成',
    rhythmDistribution: '30 日节奏分布',
    dayUnit: '日',
    keyWindows: '关键日期窗口',
    contextWindowsAriaLabel: '本期已有的记录与计划',
    rhythm: '30 日节奏',
    theme: '主题',
    suitable: '适合',
    unsuitable: '不适合',
    concernActions: '关注行动',
    concernActionsHint: '优先显示本轮更需要注意的关注',
    primaryAxis: (axis: string) => `主轴 · ${axis}`,
    notGenerated: '尚未生成',
    checklist: '本期行动清单',
    pendingConcernBody:
      '这个关注还没有进入当前 30 日窗口的生成结果。重新生成后再纳入完整解读。',
    closing: '收尾提醒',
    avoidTitle: '不建议做的事',
    reviewTitle: '复盘问题',
    evidence: '生成依据',
    monthTendencyCountsAriaLabel: '月内倾向分布',
    countUnit: '条',
  },
} as const;
